### ISSUE TITLE
建议以及路由bug

### ISSUE THREAD

**Issue by luciferid** [trensy/framework#1]
整套框架的理念不错
(1)建议建立一个qq群方便互相学习,套路这套架构 并把它添加到这个项目的首页位置
(2)路由有些问题跑不通比如
Route::bind(['get','post'],"/",function(){
       echo "hello trensy33333";
});

**Comment by trensy** [comment]
感谢关注,目前项目还没有正式对外公开，改了很多东西，文档也是旧的，等我整理整理，到时候后公开qq群
